Turn off unicode_literals
Unicode_literals was causing the regex that tidys the rows to
throw errors like below.

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 47: ordinal not in range(128)